version: '3.8'

services:
  mysql-candidates:
    image: mysql:8
    container_name: mysql-candidates
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recrusmart_candidates
    ports:
      - "3308:3306"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  candidate-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: candidate-service
    depends_on:
      - mysql-candidates
      - minio
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-candidates:3306/recrusmart_candidates
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MINIO_URL: http://minio:9000
      MINIO_ACCESSKEY: minioadmin
      MINIO_SECRETKEY: minioadmin
      JWT_SECRET: CHANGEMOI_SECRET_32_CHAR

volumes:
  minio-data:
