services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - auth-service
      - candidat-service
      - offre-service
      - intelligence-service
      - notification-service
      - entretiens-service

    networks: [recrusmart-network]
    restart: unless-stopped
  frontend:
    build: ../frontend
    ports: ["3000:80"]
    networks: [recrusmart-network]
    depends_on: [api-gateway]
    restart: unless-stopped
  auth-service:
    build: ./service-authentification
    ports: ["5000:5000"]
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongodb:27017/recrusmart_auth
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: amqp://rabbitmq
      SERVICE_NAME: auth-service
      SERVICE_HOST: auth-service
      PORT: 5000
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on: [mongodb, rabbitmq]
    networks: [recrusmart-network]
    restart: unless-stopped

  offre-service:
    build: ./service-offre
    ports: ["8081:8081"]
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongodb:27017/recrusmart_offres
      RABBITMQ_URL: amqp://rabbitmq
      SERVICE_NAME: offre-service
      SERVICE_HOST: offre-service
      PORT: 8081
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on: [mongodb, rabbitmq]
    networks: [recrusmart-network]
    restart: unless-stopped

  intelligence-service:
    build: ./service-Inteligence
    ports: ["8082:8082"]
    env_file: .env
    environment:
      SERVICE_NAME: intelligence-service
      SERVICE_HOST: intelligence-service
      PORT: 8082
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on: [rabbitmq, candidat-service]
    networks: [recrusmart-network]
    restart: unless-stopped

  notification-service:
    build: ./service-notifications
    ports: ["8083:5000"]
    env_file: .env
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      NODE_ENV: production
      GMAIL_USER: recrusmart.contact@gmail.com
      GMAIL_APP_PASSWORD: wspx czzr emjq mnzc
      MAIL_FROM: recrusmart.contact@gmail.com
      SERVICE_NAME: notification-service
      SERVICE_HOST: notification-service
      PORT: 5003
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on: [rabbitmq]
    networks: [recrusmart-network]
    restart: unless-stopped

  entretiens-service:
    build: ./service-entretiens
    ports: ["8085:4000"]
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongodb:27017/recrusmart_entretiens
      RABBITMQ_URL: amqp://rabbitmq
      JWT_SECRET: ${JWT_SECRET}
      SERVICE_NAME: entretiens-service
      SERVICE_HOST: entretiens-service
      PORT: 4000
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on: [mongodb, rabbitmq]
    networks: [recrusmart-network]
    restart: unless-stopped

  candidat-service:
    build: ./service-candidats
    ports: ["8084:8084"]
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASS}
      OFFRE_BASE_URL: http://api-gateway/api/offres
      SERVICE_NAME: candidat-service
      SERVICE_HOST: candidat-service
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on: [mysql, rabbitmq]
    networks: [recrusmart-network]
    restart: unless-stopped

  mongodb:
    image: mongo:8
    ports: ["27017:27017"]
    volumes: [mongodb_data:/data/db]
    networks: [recrusmart-network]
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports: ["3307:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes: [mysql_data:/var/lib/mysql]
    networks: [recrusmart-network]
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
    volumes: [rabbitmq_data:/var/lib/rabbitmq]
    networks: [recrusmart-network]
    restart: unless-stopped

  consul:
    image: consul:1.16
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks: [recrusmart-network]
    restart: unless-stopped

networks:
  recrusmart-network:
    driver: bridge

volumes:
  mongodb_data:
  mysql_data:
  rabbitmq_data:
