

temp_dir: null  # Use RECRUSMART_TEMP_DIR or tempfile.gettempdir()
log_level: null  # Use RECRUSMART_LOG_LEVEL or INFO
config_dir: null  # Use RECRUSMART_CONFIG_DIR or default
api:
  host: null  # Use RECRUSMART_API_HOST or 0.0.0.0
  port: null  # Use RECRUSMART_API_PORT or 8000
scoring_weights:
  skills: null  # Use RECRUSMART_SCORING_SKILLS or 8.0
  experience: null  # Use RECRUSMART_SCORING_EXPERIENCE or 20.0
  education: null  # Use RECRUSMART_SCORING_EDUCATION or 15.0
  role_fit: null  # Use RECRUSMART_SCORING_ROLE_FIT or 40.0
  projects: null  # Use RECRUSMART_SCORING_PROJECTS or 10.0