server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.11.111:3306/recrusmart_candidates
    username: nc
    password: hey hey 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

minio:
  url: http://192.168.11.111:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    name: cv

jwt:
  secret: VOTRE_SECRET_32_CARACTÈRES
