server:
  port: 8084
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  
  offre:
    base-url: http://offre-service:8081

cloudflare:
  r2:
    endpoint: ${CF_R2_ENDPOINT}
    access-key: ${CF_R2_ACCESS_KEY}
    secret-key: ${CF_R2_SECRET_KEY}
    bucket.name: ${CF_R2_BUCKET}
    public-endpoint: ${CF_R2_PUBLIC_ENDPOINT}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG     # enlève si trop verbeux
