server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql-candidates:3306/recrusmart_candidates
    username: root
    password: anass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: VOTRE_SECRET_32_CARACTÈRES
