server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recrusmart_candidates
    username: root
    password: anass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

cloudflare:
  r2:
    endpoint: https://6869463e2369d0a64cf20a934c6aa2eb.r2.cloudflarestorage.com  # Remplacer par votre vrai endpoint Cloudflare R2
    access-key: 85091b1f0894c546dbd9cf486c151f60  # Remplacer par votre vrai Access Key R2
    secret-key: 7c1ecd80a89f5357362cd8c7690488114d4011d9cf24c7d896ed31f040711469  # Remplacer par votre vrai Secret Key R2
    bucket:
      name: recrusmart-cvs  # Nom du bucket créé dans Cloudflare R2
    public-endpoint: https://pub-15ecea7a863e4583a576e62f10b10177.r2.dev

jwt:
  secret: VOTRE_SECRET_32_CARACTÈRES
